use actix_web::HttpRequest;
use fluent::{ FluentArgs };

use crate::global_state::GlobalState;
use crate::templates::{ PageParametersMain, TemplateLogin };
use crate::helpers_actix::HttpRequestHelper;
// Probably dynamically generated by a macro
// use crate::yarte::Template;
use crate::helpers_templating::PageRenderer;

use crate::translate; 

pub struct ViewLogin;

impl ViewLogin {
	pub fn render(global_state: GlobalState, req: HttpRequest) -> String {
		let template = TemplateLogin {
			str_label_username: translate!(global_state, req, "str_label_username"),
			str_label_password: translate!(global_state, req, "str_label_password"),
			str_button_login: translate!(global_state, req, "str_button_login"),
		};
		
		PageRenderer::render_main(
			&global_state, &req,
			&PageParametersMain { title_code: "title_login" },
			&template
		)
	}
}
